<?php
namespace Fingent\Mastercard\Helper;

class Countries {
	/**
	 * The single instance of the class.
	 *
	 * @var Mastercard
	 */
	private static $instance = null;

	/**
	 * PaymentController Instance.
	 *
	 * @return PaymentController instance.
	 */
	public static function get_instance() {
		if ( null === self::$instance ) {
			self::$instance = new self();
		}

		return self::$instance;
	}

	/**
	 * Constructor.
	 *
	 * @throws Exception If there's a problem connecting to the gateway.
	 */
	public function __construct() {}

	/**
	 * Return two-letter ISO country code to a three-letter ISO country code.
	 *
	 * @param string $iso2_country - The two-letter ISO country code.
	 *
	 * @return string The three-letter ISO country code.
	 */
	public function get_iso2_to_iso3() {
		return array(
			'BD' => 'BGD',
			'BE' => 'BEL',
			'BF' => 'BFA',
			'BG' => 'BGR',
			'BA' => 'BIH',
			'BB' => 'BRB',
			'WF' => 'WLF',
			'BL' => 'BLM',
			'BM' => 'BMU',
			'BN' => 'BRN',
			'BO' => 'BOL',
			'BH' => 'BHR',
			'BI' => 'BDI',
			'BJ' => 'BEN',
			'BT' => 'BTN',
			'JM' => 'JAM',
			'BV' => 'BVT',
			'BW' => 'BWA',
			'WS' => 'WSM',
			'BQ' => 'BES',
			'BR' => 'BRA',
			'BS' => 'BHS',
			'JE' => 'JEY',
			'BY' => 'BLR',
			'BZ' => 'BLZ',
			'RU' => 'RUS',
			'RW' => 'RWA',
			'RS' => 'SRB',
			'TL' => 'TLS',
			'RE' => 'REU',
			'TM' => 'TKM',
			'TJ' => 'TJK',
			'RO' => 'ROU',
			'TK' => 'TKL',
			'GW' => 'GNB',
			'GU' => 'GUM',
			'GT' => 'GTM',
			'GS' => 'SGS',
			'GR' => 'GRC',
			'GQ' => 'GNQ',
			'GP' => 'GLP',
			'JP' => 'JPN',
			'GY' => 'GUY',
			'GG' => 'GGY',
			'GF' => 'GUF',
			'GE' => 'GEO',
			'GD' => 'GRD',
			'GB' => 'GBR',
			'GA' => 'GAB',
			'SV' => 'SLV',
			'GN' => 'GIN',
			'GM' => 'GMB',
			'GL' => 'GRL',
			'GI' => 'GIB',
			'GH' => 'GHA',
			'OM' => 'OMN',
			'TN' => 'TUN',
			'JO' => 'JOR',
			'HR' => 'HRV',
			'HT' => 'HTI',
			'HU' => 'HUN',
			'HK' => 'HKG',
			'HN' => 'HND',
			'HM' => 'HMD',
			'VE' => 'VEN',
			'PR' => 'PRI',
			'PS' => 'PSE',
			'PW' => 'PLW',
			'PT' => 'PRT',
			'SJ' => 'SJM',
			'PY' => 'PRY',
			'IQ' => 'IRQ',
			'PA' => 'PAN',
			'PF' => 'PYF',
			'PG' => 'PNG',
			'PE' => 'PER',
			'PK' => 'PAK',
			'PH' => 'PHL',
			'PN' => 'PCN',
			'PL' => 'POL',
			'PM' => 'SPM',
			'ZM' => 'ZMB',
			'EH' => 'ESH',
			'EE' => 'EST',
			'EG' => 'EGY',
			'ZA' => 'ZAF',
			'EC' => 'ECU',
			'IT' => 'ITA',
			'VN' => 'VNM',
			'SB' => 'SLB',
			'ET' => 'ETH',
			'SO' => 'SOM',
			'ZW' => 'ZWE',
			'SA' => 'SAU',
			'ES' => 'ESP',
			'ER' => 'ERI',
			'ME' => 'MNE',
			'MD' => 'MDA',
			'MG' => 'MDG',
			'MF' => 'MAF',
			'MA' => 'MAR',
			'MC' => 'MCO',
			'UZ' => 'UZB',
			'MM' => 'MMR',
			'ML' => 'MLI',
			'MO' => 'MAC',
			'MN' => 'MNG',
			'MH' => 'MHL',
			'MK' => 'MKD',
			'MU' => 'MUS',
			'MT' => 'MLT',
			'MW' => 'MWI',
			'MV' => 'MDV',
			'MQ' => 'MTQ',
			'MP' => 'MNP',
			'MS' => 'MSR',
			'MR' => 'MRT',
			'IM' => 'IMN',
			'UG' => 'UGA',
			'TZ' => 'TZA',
			'MY' => 'MYS',
			'MX' => 'MEX',
			'IL' => 'ISR',
			'FR' => 'FRA',
			'IO' => 'IOT',
			'SH' => 'SHN',
			'FI' => 'FIN',
			'FJ' => 'FJI',
			'FK' => 'FLK',
			'FM' => 'FSM',
			'FO' => 'FRO',
			'NI' => 'NIC',
			'NL' => 'NLD',
			'NO' => 'NOR',
			'NA' => 'NAM',
			'VU' => 'VUT',
			'NC' => 'NCL',
			'NE' => 'NER',
			'NF' => 'NFK',
			'NG' => 'NGA',
			'NZ' => 'NZL',
			'NP' => 'NPL',
			'NR' => 'NRU',
			'NU' => 'NIU',
			'CK' => 'COK',
			'XK' => 'XKX',
			'CI' => 'CIV',
			'CH' => 'CHE',
			'CO' => 'COL',
			'CN' => 'CHN',
			'CM' => 'CMR',
			'CL' => 'CHL',
			'CC' => 'CCK',
			'CA' => 'CAN',
			'CG' => 'COG',
			'CF' => 'CAF',
			'CD' => 'COD',
			'CZ' => 'CZE',
			'CY' => 'CYP',
			'CX' => 'CXR',
			'CR' => 'CRI',
			'CW' => 'CUW',
			'CV' => 'CPV',
			'CU' => 'CUB',
			'SZ' => 'SWZ',
			'SY' => 'SYR',
			'SX' => 'SXM',
			'KG' => 'KGZ',
			'KE' => 'KEN',
			'SS' => 'SSD',
			'SR' => 'SUR',
			'KI' => 'KIR',
			'KH' => 'KHM',
			'KN' => 'KNA',
			'KM' => 'COM',
			'ST' => 'STP',
			'SK' => 'SVK',
			'KR' => 'KOR',
			'SI' => 'SVN',
			'KP' => 'PRK',
			'KW' => 'KWT',
			'SN' => 'SEN',
			'SM' => 'SMR',
			'SL' => 'SLE',
			'SC' => 'SYC',
			'KZ' => 'KAZ',
			'KY' => 'CYM',
			'SG' => 'SGP',
			'SE' => 'SWE',
			'SD' => 'SDN',
			'DO' => 'DOM',
			'DM' => 'DMA',
			'DJ' => 'DJI',
			'DK' => 'DNK',
			'VG' => 'VGB',
			'DE' => 'DEU',
			'YE' => 'YEM',
			'DZ' => 'DZA',
			'US' => 'USA',
			'UY' => 'URY',
			'YT' => 'MYT',
			'UM' => 'UMI',
			'LB' => 'LBN',
			'LC' => 'LCA',
			'LA' => 'LAO',
			'TV' => 'TUV',
			'TW' => 'TWN',
			'TT' => 'TTO',
			'TR' => 'TUR',
			'LK' => 'LKA',
			'LI' => 'LIE',
			'LV' => 'LVA',
			'TO' => 'TON',
			'LT' => 'LTU',
			'LU' => 'LUX',
			'LR' => 'LBR',
			'LS' => 'LSO',
			'TH' => 'THA',
			'TF' => 'ATF',
			'TG' => 'TGO',
			'TD' => 'TCD',
			'TC' => 'TCA',
			'LY' => 'LBY',
			'VA' => 'VAT',
			'VC' => 'VCT',
			'AE' => 'ARE',
			'AD' => 'AND',
			'AG' => 'ATG',
			'AF' => 'AFG',
			'AI' => 'AIA',
			'VI' => 'VIR',
			'IS' => 'ISL',
			'IR' => 'IRN',
			'AM' => 'ARM',
			'AL' => 'ALB',
			'AO' => 'AGO',
			'AQ' => 'ATA',
			'AS' => 'ASM',
			'AR' => 'ARG',
			'AU' => 'AUS',
			'AT' => 'AUT',
			'AW' => 'ABW',
			'IN' => 'IND',
			'AX' => 'ALA',
			'AZ' => 'AZE',
			'IE' => 'IRL',
			'ID' => 'IDN',
			'UA' => 'UKR',
			'QA' => 'QAT',
			'MZ' => 'MOZ',
		);
	}

	/**
	 * Returns the list of supported languages for the Hosted Checkout.
	 * 
	 * Key   = Language/Locale code used by the gateway
	 * Value = Human-readable language name (English + native script where applicable)
	 * @return array<string>
	 */
	// public function get_ietf_countries() {
	// 	return array(
	// 		'en'     => 'English (United States)',
	// 		'en_AU'  => 'English (Australia)',
	// 		'en_GB'  => 'English (UK)',
	// 		'en_CA'  => 'English (Canada)',
	// 		'en_ZA'  => 'English (South Africa)',
	// 		'en_NZ'  => 'English (New Zealand)',
	// 		'af'     => 'Afrikaans (Afrikaans)',
	// 		'am'     => 'አማርኛ (Amharic)',
	// 		'ar'     => 'العربية (Arabic)',
	// 		'arn'    => 'Mapudungun (Mapudungun)',
	// 		'ary'    => 'الدارجة المغربية (Moroccan Arabic)',
	// 		'as'     => 'অসমীয়া (Assamese)',
	// 		'az'     => 'Azərbaycan (Azerbaijani)',
	// 		'ba'     => 'Башҡорт (Bashkir)',
	// 		'be'     => 'беларуская (Belarusian)',
	// 		'bg'     => 'български (Bulgarian)',
	// 		'bn'     => 'বাংলা (Bengali)',
	// 		'bo'     => 'བོད་ཡིག (Tibetan)',
	// 		'br'     => 'brezhoneg (Breton)',
	// 		'bs'     => 'bosanski/босански (Bosnian)',
	// 		'ca'     => 'català (Catalan)',
	// 		'ckb'    => 'کوردیی ناوەندی (Central Kurdish)',
	// 		'co'     => 'Corsu (Corsican)',
	// 		'cs'     => 'čeština (Czech)',
	// 		'cy'     => 'Cymraeg (Welsh)',
	// 		'da'     => 'dansk (Danish)',
	// 		'de'     => 'Deutsch (German)',
	// 		'dsb'    => 'dolnoserbšćina (Lower Sorbian)',
	// 		'dv'     => 'ދިވެހިބަސް (Divehi)',
	// 		'el'     => 'Ελληνικά (Greek)',
	// 		'es'     => 'español (Spanish)',
	// 		'et'     => 'eesti (Estonian)',
	// 		'eu'     => 'euskara (Basque)',
	// 		'fa'     => 'فارسى (Persian)',
	// 		'fi'     => 'suomi (Finnish)',
	// 		'fil'    => 'Filipino (Filipino)',
	// 		'fo'     => 'føroyskt (Faroese)',
	// 		'fr'     => 'français (French)',
	// 		'fy'     => 'Frysk (Frisian)',
	// 		'ga'     => 'Gaeilge (Irish)',
	// 		'gd'     => 'Gàidhlig (Scottish Gaelic)',
	// 		'gil'    => 'Taetae ni Kiribati (Gilbertese)',
	// 		'gl'     => 'galego (Galician)',
	// 		'gsw'    => 'Schweizerdeutsch (Swiss German)',
	// 		'gu'     => 'ગુજરાતી (Gujarati)',
	// 		'ha'     => 'Hausa (Hausa)',
	// 		'he'     => 'עברית (Hebrew)',
	// 		'hi'     => 'हिंदी (Hindi)',
	// 		'hr'     => 'hrvatski (Croatian)',
	// 		'hsb'    => 'hornjoserbšćina (Upper Sorbian)',
	// 		'hu'     => 'magyar (Hungarian)',
	// 		'hy'     => 'Հայերեն (Armenian)',
	// 		'id'     => 'Bahasa Indonesia (Indonesian)',
	// 		'ig'     => 'Igbo (Igbo)',
	// 		'ii'     => 'ꆈꌠꁱꂷ (Yi)',
	// 		'is'     => 'íslenska (Icelandic)',
	// 		'it'     => 'italiano (Italian)',
	// 		'iu'     => 'ᐃᓄᒃᑎᑐᑦ (ᑲᓇᑕ) (Inuktitut)',
	// 		'ja'     => '日本語 (Japanese)',
	// 		'ka'     => 'ქართული (Georgian)',
	// 		'kk'     => 'Қазақша (Kazakh)',
	// 		'kl'     => 'kalaallisut (Greenlandic)',
	// 		'km'     => 'ខ្មែរ (Khmer)',
	// 		'kn'     => 'ಕನ್ನಡ (Kannada)',
	// 		'ko'     => '한국어 (Korean)',
	// 		'kok'    => 'कोंकणी (Konkani)',
	// 		'ku'     => 'Kurdî / کورد(ی (Kurdish)',
	// 		'ky'     => 'Кыргыз (Kyrgyz)',
	// 		'lb'     => 'Lëtzebuergesch (Luxembourgish)',
	// 		'lo'     => 'ລາວ (Lao)',
	// 		'lt'     => 'lietuvių (Lithuanian)',
	// 		'lv'     => 'latviešu (Latvian)',
	// 		'mi'     => 'Reo Māori (Maori)',
	// 		'mk'     => 'македонски јазик (Macedonian)',
	// 		'ml'     => 'മലയാളം (Malayalam)',
	// 		'mn'     => 'Монгол хэл (Mongolian)',
	// 		'moh'    => 'Kanien\'kéha (Mohawk)',
	// 		'mr'     => 'मराठी (Marathi)',
	// 		'ms'     => 'Bahasa Malaysia (Malay)',
	// 		'mt'     => 'Malti (Maltese)',
	// 		'my'     => 'မြန်မာဘာသာ (Burmese)',
	// 		'nb'     => 'norsk (bokmål)',
	// 		'ne'     => 'नेपाली (नेपाल)',
	// 		'nl'     => 'Nederlands (Dutch)',
	// 		'nn'     => 'norsk (nynorsk)',
	// 		'nn'     => 'norsk (Norwegian - Nynorsk)',
	// 		'no'     => 'norsk (Norwegian)',
	// 		'oc'     => 'occitan (Occitan)',
	// 		'or'     => 'ଓଡ଼ିଆ (Odia)',
	// 		'pap'    => 'Papiamentu (Papiamento)',
	// 		'pa'     => 'ਪੰਜਾਬੀ / پنجابی (Punjabi)',
	// 		'pl'     => 'polski (Polish)',
	// 		'prs'    => 'درى (Dari)' ,
	// 		'ps'     => 'پښتو (Pashto)',
	// 		'pt'     => 'português (Portuguese)',
	// 		'quc'    => 'K\'iche (Kiche)',
	// 		'qu'     => 'runasimi (Quechua)',
	// 		'rm'     => 'Rumantsch (Romansh)',
	// 		'ro'     => 'română (Romanian)',
	// 		'ru'     => 'русский (Russian)',
	// 		'rw'     => 'Kinyarwanda (Kinyarwanda)',
	// 		'sa'     => 'संस्कृत (Sanskrit)',
	// 		'sah'    => 'саха (Yakut)',
	// 		'se'     => 'davvisámegiella (Sami - Northern)',
	// 		'sma'    => 'åarjelsaemiengiele (Sami - Southern)',
	// 		'smj'    => 'julevusámegiella (Sami - Lule)',
	// 		'smn'    => 'sämikielâ (Sami - Inari)',
	// 		'sms'    => 'sääʹmǩiõll (Sami - Skolt)',
	// 		'si'     => 'සිංහල (Sinhala)',
	// 		'sk'     => 'slovenčina (Slovak)',
	// 		'sl'     => 'slovenščina (Slovenian)',
	// 		'sq'     => 'shqip (Albanian)',
	// 		'sr'     => 'srpski / српски (Serbian)',
	// 		'st'     => 'Sesotho (Sesotho)',
	// 		'sv'     => 'svenska (Swedish)',
	// 		'sw'     => 'Kiswahili (Kiswahili)',
	// 		'syc'    => 'ܣܘܪܝܝܐ (Syriac)' ,
	// 		'ta'     => 'தமிழ் (Tamil)',
	// 		'te'     => 'తెలుగు (Telugu)',
	// 		'tg'     => 'Тоҷикӣ (Tajik)',
	// 		'th'     => 'ไทย (Thai)',
	// 		'tk'     => 'türkmençe (Turkmen)',
	// 		'tn'     => 'Setswana (Tswana)',
	// 		'tr'     => 'Türkçe (Turkish)',
	// 		'tt'     => 'Татарча (Tatar)',
	// 		'tzm'    => 'Tamazight (Tamazight)',
	// 		'ug'     => 'ئۇيغۇرچە (Uyghur) ',
	// 		'uk'     => 'українська (Ukrainian)',
	// 		'ur'     => 'اُردو(Urdu)',
	// 		'uz'     => 'Uzbek / Ўзбек (Uzbek)',
	// 		'vi'     => 'Tiếng Việt (Vietnamese)',
	// 		'wo'     => 'Wolof (Wolof)',
	// 		'xh'     => 'isiXhosa (Xhosa)',
	// 		'yo'     => 'Yoruba (Yoruba)',
	// 		'zh_HK'  => '香港中文 (Hong Kong Chinese)',
	// 		'zh_TW'  => '繁體中文 (Traditional Chinese)',
	// 		'zh_CN'  => '简体中文 (Simplified Chinese)',
	// 		'zu'     => 'isiZulu (Zulu)',
	// 	);
	// }

	/**
	 * Returns the list of supported languages for the Hosted Session.
	 * 
	 * Key   = Language/Locale code used by the gateway
	 * Value = Human-readable language name (English + native script where applicable)
	 * @return array<string>
	 */
	// public function get_hs_countries() {
	// 	return array(
	// 		'en'     => 'English',
	// 		'zh_HK'  => '香港中文 (Hong Kong Chinese)',
	// 		'zh_TW'  => '繁體中文 (Traditional Chinese)',
	// 		'zh_CN'  => '简体中文 (Simplified Chinese)',
	// 		'el'     => 'Ελληνικά (Greek)',
			
	// 	);
	// }

	/**
	 * Return translation for "Ordered Goods" based on locale.
	 *
	 * @param string $locale Locale code (e.g., en_US, fr, de_DE).
	 * @return string
	 */
	public function get_order_summary_text( $locale ) {
			$translations = array(
				'en'     => 'Ordered Goods',
				'en_AU'  => 'Ordered Goods',
				'en_GB'  => 'Ordered Goods',
				'en_CA'  => 'Ordered Goods',
				'en_ZA'  => 'Ordered Goods',
				'en_NZ'  => 'Ordered Goods',
				'af'     => 'Bestelde Goedere',
				'am'     => 'ትእዛዝ የተደረጉ ዕቃዎች',
				'ar'     => 'البضائع المطلوبة',
				'arn'    => 'Chi we püllkülen mew',
				'ary'    => 'السلع المطلوبة',
				'as'     => 'অৰ্ডাৰ কৰা সামগ্ৰী',
				'az'     => 'Sifariş Edilmiş Mallar',
				'ba'     => 'Заказланған тауарҙар',
				'be'     => 'Замоўленыя тавары',
				'bg'     => 'Поръчани стоки',
				'bn'     => 'অর্ডারকৃত পণ্য',
				'bo'     => 'མངགས་འདེབས་བྱས་པའི་ལག་ཆས།',
				'br'     => 'Madober gourc’hemennet',
				'bs'     => 'Narudžena roba',
				'ca'     => 'Mercaderies demanades',
				'ckb'    => 'کالای داواکراو',
				'co'     => 'Merci urdinate',
				'cs'     => 'Objednané zboží',
				'cy'     => 'Nwyddau a Archebwyd',
				'da'     => 'Bestilte varer',
				'de'     => 'Bestellte Waren',
				'dsb'    => 'Zawězane twary',
				'dv'     => 'އޯޑަރު ކުރެވި ބޮޑުކުޅު',
				'el'     => 'Παραγγελθέντα προϊόντα',
				'es'     => 'Bienes solicitados',
				'et'     => 'Tellitud kaubad',
				'eu'     => 'Eskatutako ondasunak',
				'fa'     => 'کالاهای سفارش‌شده',
				'fi'     => 'Tilatut tavarat',
				'fil'    => 'Mga inorder na produkto',
				'fo'     => 'Keypt vørur',
				'fr'     => 'Produits commandés',
				'fy'     => 'Bestelde guod',
				'ga'     => 'Earraí a Ordaíodh',
				'gd'     => 'Bathar air an òrdachadh',
				'gil'    => 'Kabwarabwara ae reke',
				'gl'     => 'Mercadorías solicitadas',
				'gsw'    => 'Bstelligti Wär',
				'gu'     => 'ઓર્ડર કરેલ માલ',
				'ha'     => 'Kayayyakin da aka bayar da oda',
				'he'     => 'סחורה שהוזמנה',
				'hi'     => 'ऑर्डर किए गए सामान',
				'hr'     => 'Naručena roba',
				'hsb'    => 'Zamóžene twary',
				'hu'     => 'Megrendelt áruk',
				'hy'     => 'Պատվիրած ապրանքներ',
				'id'     => 'Barang yang dipesan',
				'ig'     => 'Ngwa ndị e nyere iwu',
				'ii'     => 'ꄮꑤꄻꌠꁱ',
				'is'     => 'Pantaðar vörur',
				'it'     => 'Merce ordinata',
				'iu'     => 'ᐊᓂᕐᓂᖅᑕᐅᔪᖅ ᐃᑲᔪᖅ',
				'ja'     => '注文された商品',
				'ka'     => 'შეკვეთილი საქონელი',
				'kk'     => 'Тапсырыс берілген тауарлар',
				'kl'     => 'Pisiassat inniminnerneqarsimasut',
				'km'     => 'ទំនិញដែលបានបញ្ជា',
				'kn'     => 'ಆರ್ಡರ್ ಮಾಡಲಾದ ಸರಕುಗಳು',
				'ko'     => '주문된 상품',
				'kok'    => 'ऑर्डर केलेल्या वस्तू',
				'ku'     => 'Malên ferman kirî',
				'ky'     => 'Буйрутма берилип алынган товарлар',
				'lb'     => 'Bestallt Wueren',
				'lo'     => 'ສິນຄ້າທີ່ສັ່ງ',
				'lt'     => 'Užsakytos prekės',
				'lv'     => 'Pasūtītās preces',
				'mi'     => 'Ngā taonga kua tonoa',
				'mk'     => 'Нарачани производи',
				'ml'     => 'ഓർഡർ ചെയ്ത സാധനങ്ങൾ',
				'mn'     => 'Захиалсан бараа',
				'moh'    => 'Oniáhte ne onekwén:na',
				'mr'     => 'ऑर्डर केलेला माल',
				'ms'     => 'Barang yang dipesan',
				'mt'     => 'Oġġetti ordnati',
				'my'     => 'မှာကြန်းထားသော ပစ္စည်းများ',
				'nb'     => 'Bestilte varer',
				'ne'     => 'अर्डर गरिएका सामान',
				'nl'     => 'Bestelde goederen',
				'nn'     => 'Bestilte varer',
				'no'     => 'Bestilte varer',
				'oc'     => 'Mercandisas comandadas',
				'or'     => 'ଆଦେଶ କରାଯାଇଥିବା ସମଗ୍ରୀ',
				'pap'    => 'Artíkul skibi',
				'pa'     => 'ਮੰਗੇ ਹੋਏ ਸਮਾਨ',
				'pl'     => 'Zamówione towary',
				'prs'    => 'مال‌های سفارش‌شده',
				'ps'     => 'غوښتل شوي توکي',
				'pt'     => 'Bens encomendados',
				'quc'    => 'K\'o wi qach\'aj',
				'qu'     => 'Mañakusqa allin',
				'rm'     => 'Rauba dumandada',
				'ro'     => 'Produse comandate',
				'ru'     => 'Заказанные товары',
				'rw'     => 'Ibicuruzwa byatumijwe',
				'sa'     => 'आदेशित वस्तूनि',
				'sah'    => 'Ыраах таҥналаах тавара',
				'se'     => 'Deavdán gálvvut',
				'sma'    => 'Beställda varutjåangh',
				'smj'    => 'Gålmmådahka gálvvut',
				'smn'    => 'Tiõrvâttem tavârr',
				'sms'    => 'Pâstõõttem tavâʹrr',
				'si'     => 'ඇනවුම් කළ අයිතම',
				'sk'     => 'Objednaný tovar',
				'sl'     => 'Naročeno blago',
				'sq'     => 'Mallrat e porositura',
				'sr'     => 'Наруђена роба',
				'st'     => 'Lintho tse laetsoeng',
				'sv'     => 'Beställda varor',
				'sw'     => 'Bidhaa zilizoagizwa',
				'syc'    => 'ܩܰܢܘܢܳܝ̈ܳܐ ܕܐܶܬܩܰܛܠܘ',
				'ta'     => 'ஆர்டர் செய்யப்பட்ட பொருட்கள்',
				'te'     => 'ఆర్డర్ చేసిన వస్తువులు',
				'tg'     => 'Молҳои фармоишшуда',
				'th'     => 'สินค้าที่สั่งซื้อ',
				'tk'     => 'Sargyt edilen harytlar',
				'tn'     => 'Dilwana tse laetsweng',
				'tr'     => 'Sipariş edilen mallar',
				'tt'     => 'Заказланган товарлар',
				'tzm'    => 'Tifin n tsuwrnin',
				'ug'     => 'بىئېتىلگەن ماللار',
				'uk'     => 'Замовлені товари',
				'ur'     => 'آرڈر کی گئی اشیاء',
				'uz'     => 'Buyurtma qilingan tovarlar',
				'vi'     => 'Hàng đã đặt',
				'wo'     => 'Mbëj-mi ñu laaj',
				'xh'     => 'Iimpahla ezalelwe',
				'yo'     => 'Àwọn ohun tí a pàṣẹ',
				'zh_HK'  => '已訂購的商品',
				'zh_TW'  => '已訂購的商品',
				'zh_CN'  => '已订购的商品',
				'zu'     => 'Izimpahla eziodiwe',
			);

		$locale = is_string( $locale ) ? trim( $locale ) : '';

		if ( isset( $translations[ $locale ] ) ) {
			return $translations[ $locale ];
		}

		if ( strpos( $locale, '_' ) !== false ) {
			$primary = substr( $locale, 0, strpos( $locale, '_' ) );
			if ( isset( $translations[ $primary ] ) ) {
				return $translations[ $primary ];
			}
		}

		return 'Ordered Goods';
	}
}
